import Head from "next/head";
import Image from "next/image";
import Post from "../components/post";
import { getPosts } from "../lib/posts";

export async function getStaticProps() {
  // fetch list of posts
  const postList = await getPosts();

  return {
    props: {
      postList,
    },
  };
}

export default function IndexPage({ postList }) {
  return (
    <section>
      <Head>
        <title>Next.js Static</title>
        <meta name="description" content="Generated by Vulcan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="header">
        <Image src="/azion.svg" width={100} height={24} alt="Azion Logo" />
      </div>
      <div class="content">
        <Image src="/next.svg" width={200} height={100} alt="Next Logo" />
        <h1>Next.js - Static (output export)</h1>
        {/* remove the comment to list the posts */}
        {/* <div className="posts"> 
          {postList.map((post) => (
            <Post {...post} key={post.id} />
          ))}
        </div> */}
      </div>
      <div class="footer">
        <a
          href="https://www.azion.com/en/documentation/"
          rel="noreferrer"
          target="_blank"
        >
          <h1>Docs</h1>
          <p>
            Besides providing structure, it allows interactions to occur with
            the surface of the element, thus enabling it to have states.
          </p>
        </a>
        <a href="https://medium.com/aziontech" target="_blank" rel="noreferrer">
          <div>
            <h1>Medium</h1>
            <p>
              Dive deep into our platform's use cases on Medium and join a
              community where developers connect, collaborate, and innovate.
            </p>
          </div>
        </a>
        <a
          href="https://twitter.com/aziontech"
          target="_blank"
          rel="noreferrer"
        >
          <div>
            <h1>X (formerly Twitter)</h1>
            <p>
              Explore our features in-depth and find out what's new on our
              platform.
            </p>
          </div>
        </a>
        <a
          href="https://discord.gg/Yp9N7RMVZy"
          target="_blank"
          rel="noreferrer"
        >
          <div>
            <h1>Discord</h1>
            <p>
              A space for developers to connect, get involved and collaborate.
            </p>
          </div>
        </a>
      </div>
    </section>
  );
}
