import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Redirect Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="grid">
          <h1>Redirect Page</h1>
        </div>
      </main>
    </>
  );
}
